import * as stylex from '@stylexjs/stylex'
import { tokens } from './tokens.stylex'

const hover = '@media (hover: hover)'

export const ui = stylex.create({
  body: {
    minHeight: '100dvh',
    backgroundColor: tokens.bg,
    color: tokens.text,
    fontFamily: tokens.font,
    fontSize: tokens.textMd,
    lineHeight: 1.45,
    fontOpticalSizing: 'auto',
    WebkitFontSmoothing: 'antialiased',
  },
  iconButton: {
    width: '2.25rem',
    height: '2.25rem',
    padding: 0,
    borderRadius: tokens.radiusPill,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: tokens.text,
    backgroundColor: 'transparent',
    [hover]: {
      ':hover': {
        backgroundColor: tokens.chip,
      },
    },
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    padding: '0.45rem 0.75rem',
    borderRadius: tokens.radiusPill,
    backgroundColor: tokens.chip,
    color: tokens.text,
    fontSize: tokens.textSm,
    lineHeight: 1.2,
  },
  ghost: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    padding: '0.5rem 0.75rem',
    borderRadius: tokens.radiusPill,
    color: tokens.muted,
    backgroundColor: 'transparent',
    fontSize: tokens.textSm,
    [hover]: {
      ':hover': {
        backgroundColor: tokens.chip,
      },
    },
  },
  ghostOn: {
    color: tokens.accent,
  },
  pillow: {
    width: '100%',
    display: 'flex',
    alignItems: 'flex-end',
    gap: '0.75rem',
    textAlign: 'left',
    borderRadius: tokens.radiusPillow,
    backgroundColor: tokens.chip,
    color: tokens.text,
    fontSize: tokens.textSm,
    lineHeight: 1.4,
    padding: '0.875rem 1.25rem',
  },
  field: {
    flex: 1,
    minWidth: 0,
    fieldSizing: 'content',
    maxHeight: '9rem',
    overflow: 'auto',
    backgroundColor: 'transparent',
    color: 'inherit',
    font: 'inherit',
    lineHeight: 'inherit',
  },
  muted: {
    color: tokens.muted,
    fontSize: tokens.textSm,
  },
  avatar: {
    position: 'relative',
    width: '1.5rem',
    height: '1.5rem',
    borderRadius: tokens.radiusPill,
    backgroundColor: tokens.tint,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
    color: tokens.text,
    fontSize: tokens.textXs,
    fontWeight: 600,
    lineHeight: 1,
    userSelect: 'none',
  },
  avatarImg: {
    position: 'absolute',
    left: 0,
    width: '100%',
    maxWidth: 'none',
    height: 'calc(100% + 100% / 1.5)',
    top: 'calc(-100% / 1.5 + 100% * 3.5 / 6)',
    objectFit: 'cover',
  },
  card: {
    position: 'relative',
    aspectRatio: '9 / 14',
    borderRadius: tokens.radiusCard,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    backgroundColor: 'transparent',
    color: tokens.text,
    padding: '1.25rem 1.5rem',
  },
  cardEmpty: {
    borderWidth: '0.5px',
    borderStyle: 'dashed',
    borderColor: 'color-mix(in srgb, #737373 35%, transparent)',
  },
  cardMedia: {
    color: tokens.onMedia,
  },
  cardButton: {
    cursor: 'pointer',
    textAlign: 'left',
    font: 'inherit',
    [hover]: {
      ':hover': {
        opacity: 0.92,
      },
    },
  },
  cardImg: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    zIndex: 0,
  },
  cardImgBlur: {
    filter: 'blur(1.125rem)',
    transform: 'scale(1.12)',
  },
  scrim: {
    position: 'absolute',
    inset: 0,
    zIndex: 1,
    pointerEvents: 'none',
    backgroundImage:
      'linear-gradient(to top, oklch(0 0 0 / 0.34), oklch(0 0 0 / 0.08) 46%, transparent 62%)',
  },
  scrimFlat: {
    backgroundColor: 'color-mix(in srgb, #ffffff 78%, transparent)',
    '@media (prefers-color-scheme: dark)': {
      backgroundColor: 'color-mix(in srgb, #000000 78%, transparent)',
    },
  },
  cardBody: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
  },
  cardTitle: {
    fontSize: tokens.textMd,
    fontWeight: 600,
    letterSpacing: '-0.01em',
    textAlign: 'center',
    textShadow: tokens.shadow,
  },
  cardTitlePlain: {
    textAlign: 'left',
    textShadow: 'none',
    marginBottom: '0.75rem',
  },
  ring: {
    position: 'absolute',
    inset: 0,
    zIndex: 5,
    borderRadius: 'inherit',
    boxShadow: 'inset 0 0 0 4px #ffffffaa',
    pointerEvents: 'none',
  },
})
